"""initial migration

Revision ID: 430c885d3586
Revises: 
Create Date: 2024-01-17 12:58:10.601216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '430c885d3586'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_image_association',
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['product_image.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['add_product.id'], )
    )
    op.add_column('add_product', sa.Column('name', sa.String(length=80), nullable=False))
    op.add_column('add_product', sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('add_product', sa.Column('discount', sa.Integer(), nullable=True))
    op.add_column('add_product', sa.Column('stock', sa.Integer(), nullable=False))
    op.add_column('add_product', sa.Column('colors', sa.Text(), nullable=False))
    op.add_column('add_product', sa.Column('description', sa.Text(), nullable=False))
    op.add_column('add_product', sa.Column('pub_date', sa.DateTime(), nullable=False))
    op.add_column('add_product', sa.Column('brand_id', sa.Integer(), nullable=False))
    op.add_column('add_product', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'add_product', 'brand', ['brand_id'], ['id'])
    op.create_foreign_key(None, 'add_product', 'category', ['category_id'], ['id'])
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'username',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
    op.drop_constraint(None, 'add_product', type_='foreignkey')
    op.drop_constraint(None, 'add_product', type_='foreignkey')
    op.drop_column('add_product', 'category_id')
    op.drop_column('add_product', 'brand_id')
    op.drop_column('add_product', 'pub_date')
    op.drop_column('add_product', 'description')
    op.drop_column('add_product', 'colors')
    op.drop_column('add_product', 'stock')
    op.drop_column('add_product', 'discount')
    op.drop_column('add_product', 'price')
    op.drop_column('add_product', 'name')
    op.drop_table('product_image_association')
    op.drop_table('product_image')
    # ### end Alembic commands ###
